name: Luxe VIP Suite Deploy App Workflow

on:
  push:
    branches:
      - staging
      - master

jobs:
  staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /var/www/luxesuite-frontend
            rm -rf /var/www/luxesuite-frontend/.next/cache
            git fetch origin staging
            git checkout staging
            git pull origin staging
            rm -rf /var/www/luxesuite-frontend/.next/cache
            pm2 restart luxesuite-frontend || pm2 start npm --name "luxesuite-frontend" -- start -- -p 3001

  production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          envs: COMPOSER_ALLOW_SUPERUSER
          script: |
            cd /var/www/luxesuite-frontend
            git fetch origin master
            git checkout master
            git pull origin master
            pm2 restart luxesuite-frontend || pm2 start npm --name "luxesuite-frontend" -- start -- -p 3001
